---

- hosts: all
  become: true
  tasks:
  
  - name: install apache and php on all servers with different distros
    package:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes
